language: python

matrix:
  include:
    - python: "2.7"
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-scipy

    - python: "3.6"
    # PyPy versions
    - python: pypy
    - python: pypy3

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - time

install:
  - pip install coveralls pylint
  - pip install .

# command to run tests
script:
 - nosetests --with-coverage --cover-package=rebench
 - (cd rebench && rebench -N ../rebench.conf executor:TestRunner2)
 - pylint rebench

after_success:
  coveralls
