name: CI

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    name: "Ubuntu Latest ${{ matrix.python-version }}"

    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout ReBench
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install .

      - name: Install PyTest
        run: pip install pytest

      - name: Run PyTest
        run: pytest

      - name: Install and run PyLint
        run: |
          pip install pylint
          pylint rebench
        if: matrix.python-version == '3.11'
